### ISSUE TITLE
Change issues, notes, examples to include NL language

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#10]
Examples, Editor's Note, Warning, Issue are still only in English and we would also like to have those in Dutch. Therefore, the proposed solution is to include these in the l10n.js:
```
note:			"Noot"
editors_note:	        "Redactionele Noot"
example:		"Voorbeeld"
issue:			"Probleem"
warning:		"Waarschuwing"
```
And adjust both js/core/examples.js as js/core/issues-notes.js to include l10.js.

**Comment by marcoscaceres** [comment]
Shipped in v11.0.1 upstream.
