### ISSUE TITLE
data-include + section input

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#101]
As a user it would be good if it were possible to add additional HTML-code to a data-include. At the moment when a data-include is used, it is not possible to add further code. For example, this does not work:
```html
<section data-include="test.html">
    <section id="add-section">
        <p> ... </p>
    </section>
</section
```
It would be better if childelements in the `<section>` are included after the data-include content is included, thus merging in the `<section>`.

**Comment by marcoscaceres** [comment]
Im not sure we want to do that, as we would then need to decide if the included text would come before or after the inner text. The right way to do it is to just nest the sections, which would give you the exact same result:

```html
<section>
<section data-include=x.html>
</section>
<section>
Hi!
</section>
</section>
</section>
```

**Comment by marcoscaceres** [comment]
Remember you can also use https://github.com/w3c/respec/wiki/data-include-replace

**Comment by marcoscaceres** [comment]
The `data-include-replace` will solve the case above too, that is.

**Comment by dhvenema** [comment]
data-include-replace=true does the job :)
