### ISSUE TITLE
Back-to-top not working

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#104]
It looks like the back-to-top arrow (pointing to `#toc`) at the bottom of the respec page is not working when the ToC is popped out. However, it does work when the ToC is collapsed (https://github.com/w3c/tr-design/).

**Comment by thijsbrentjens** [comment]
Check if this can be changed to the h1 element, with id="title". Check at W3C

**Comment by marcoscaceres** [comment]
This was fixed on the w3c side a few months ago.

**Comment by thijsbrentjens** [comment]
Thanks, I just noticed in our new version too. Thanks.
