### ISSUE TITLE
Canonical URI

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#105]
One of the main reasons to switch to HTML-documents for standards, is so users could more easily find and access said standards. In order to provide that experience, the canonical URI for the Geonovum respec ought to be set up properely in https://github.com/Geonovum/respec/blob/develop/src/geonovum/seo.js.

Additionally, look at other SEO elements:
* `<meta name="description" content="">`
* `<meta name="keywords" content="">`
* `<meta name="author" content="">`

See: https://support.google.com/webmasters/answer/79812?hl=nl
http://static.googleusercontent.com/media/www.google.com/en//webmasters/docs/search-engine-optimization-starter-guide.pdf

**Comment by dhvenema** [comment]
Canonical URL and meta description were added in https://github.com/Geonovum/respec/pull/108.

**Comment by dhvenema** [comment]
Pages give this error:
```
TypeError: e.canonicalURI is undefined
Stacktrace:
e.run@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:500788
i/<@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:213525
n@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:178854
l/<@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:179898
a/</e[t]@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:179030
r@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:212865
i/</<@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:213015
i/<@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:212813
o/</</<@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:213835
o/<@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:213132
e/<@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:214450
n@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:178854
l/<@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:179898
a/</e[t]@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:179030
r@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:212865
r/<@https://tools.geostandaarden.nl/respec/builds/respec-geonovum.js:1:212963
```

**Comment by dhvenema** [comment]
Added in build: https://github.com/Geonovum/respec/commit/6d79d0572fcd30f2d035c421acafc4e626158e10

**Comment by lvdbrink** [comment]
Check if solved.

**Comment by thijsbrentjens** [comment]
Is working properly.

**Comment by thijsbrentjens** [comment]
Deployed to production
