### ISSUE TITLE
Starting page on docs.geostandaarden

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#113]
For a user it would be good to have a starting page that presents an overview of all standards/documentation stored on docs.geostandaarden.nl. See https://www.w3.org/TR/, as an example.

**Comment by thijsbrentjens** [comment]
In samenwerking met Yvonne oppakken

**Comment by thijsbrentjens** [comment]
De vraag is of we het volledig automatisch kunnen doen, dat zou misschien nog het mooiste zijn. En/of we ook met redirects kunnen gaan werken op de huidige server om duplicaten te voorkomen.

**Comment by thijsbrentjens** [comment]
1. make a list of docs (pdfs) that explicitly need to be in the list
1. make a list of directories/docs to be ignored
1. automatically list all the latest versions (only) per pubDomain

**Comment by thijsbrentjens** [comment]
First implementation is done (https://docs.geostandaarden.nl/). See repo and initial docs in https://github.com/Geonovum/respec-utils
