### ISSUE TITLE
Previous version not working

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#126]
When previousPUblishDate and previousMaturity are set in the config, respec throws an error saying that previousStatus is missing. I think this could be a bug in our fork (src/geonovum/headers.js is testing for previousStatus, not previousMaturity). If I add previousStatus to the config as well, the whole header section is not generated. i.e. the `<body>` starts with `<section id="abstract">` instead of `<div class="head">`

**Comment by marcoscaceres** [comment]
Fixed comment above... note that if you write a HTML tag, github will treat it as real html, so be sure to always wrap html in using a back tick: "`"  characters. To see what I mean, click on the edit "✎" button in the comment box above.

**Comment by thijsbrentjens** [comment]
Needs more testing and possible fixes for Geonovum workflow. 
Testcases: 
MD profile: https://docs.geostandaarden.nl/md/mdprofiel-iso19115/ and Whitepaper Standaarden

**Comment by thijsbrentjens** [comment]
Fully working correct example: https://docs.geostandaarden.nl/wp/basis-wpgs/

**Comment by thijsbrentjens** [comment]
The MD profile and Whitepaper have different format for the last part of the URI for the previous version:
MD: {specStatus}-{specType}-{shortName}-{date}
Whitepaper: {specStatus}-{shortName}-{date}

We need to decide if this is okay and if so, what logic to use for the URI. E.g. for a GN-BASIS doc, don't use the specType. (If that makes sense at all)

**Comment by lvdbrink** [comment]
We should use one format for all URIs. Probably the differences that exist are due to manual tweaking...

**Comment by thijsbrentjens** [comment]
From the docs: structure for full URIs (like previousVersion) shall be: 
{specStatus}-{specType}-{shortName}-{date}

@lvdbrink this means we might need to update the Whitepaper to reflect the proper URLs. Or accept that for now we use the snapshot we have made and for new versions make sure we point .

**Comment by thijsbrentjens** [comment]
Wiki updated to reflect this: https://github.com/Geonovum/respec/wiki/versionURIs
