### ISSUE TITLE
Variable of publishDate is not filled in at the "datetime" attribute of <time> tag. publishDate: "2017-11-10",

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/respec#127]
Variabele van publishDate wordt niet ingevuld bij attribuut "datetime" van <time>-tag.
publishDate: "2017-11-10",

Toelichting:

W3C-validator fout:
-------------------
Error: Bad value  for attribute datetime on element time: The literal did not satisfy the time-datetime format.
From line 323, column 13; to line 323, column 77
          <time property="dcterms:issued" class="dt-published" datetime="">

Treedt op bij:
--------------
<time property="dcterms:issued" class="dt-published" datetime="">
      10 november 2017
    </time>

**Comment by thijsbrentjens** [comment]
Testen of dit is opgelost na update ReSpec. Notitie Thijs: gaat om het time-element in de header

**Comment by thijsbrentjens** [comment]
Lijkt opgelost na update ReSpec.
