### ISSUE TITLE
Bij kopje rechtenbeleid wordt inhoud (div) niet geplaatst in <dd>-tag.

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/respec#128]
W3C-validator fout:
-------------------
Error: Element div not allowed as child of element dl in this context. (Suppressing further errors from this subtree.)
From line 360, column 13; to line 360, column 61
          <div class="copyright" style="margin: 0.25em 0;">↩     
Contexts in which element div may be used:
Where flow content is expected.
As a child of a dl element.
Content model for element dl:
Either:Zero or more groups each consisting of one or more dt elements followed by one or more dd elements, optionally intermixed with script-supporting elements.
Or: One or more div elements, optionally intermixed with script-supporting elements.

met gerelateerde fout:
----------------------
Error: Element dl is missing a required instance of child element dd.
From line 370, column 9; to line 370, column 13
>↩        </dl>↩     
Content model for element dl:
Either:Zero or more groups each consisting of one or more dt elements followed by one or more dd elements, optionally intermixed with script-supporting elements.
Or: One or more div elements, optionally intermixed with script-supporting elements.
               
Treedt op bij:
--------------
   <dt>Rechtenbeleid:</dt>
            <div class="copyright" style="margin: 0.25em 0;">
                <abbr title="Naamsvermelding-GeenAfgeleideWerken 3.0 Nederland">
      <a href="https://creativecommons.org/licenses/by-nd/3.0/nl/">
        <img src="https://tools.geostandaarden.nl/respec/style/logos/CC-Licentie.svg" alt="Naamsvermelding-GeenAfgeleideWerken 3.0 Nederland" width="115px" height="40px">
      </a>
    </abbr>
                <div style="display:inline-block; vertical-align:top">
                    <p style="font-size: small;">Naamsvermelding-GeenAfgeleideWerken 3.0 Nederland<br>(CC BY-ND 3.0)</p>
                </div>
            </div>

**Comment by lvdbrink** [comment]
Tested, solved.
