### ISSUE TITLE
CC-licentie img attributes bevatten tekst i.p.v. waarden

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/respec#129]
W3C Validator fout:

 Bad value 115px for attribute width on element img: Expected a digit but saw p instead.

`<img src="https://tools.geostandaarden.nl/respec/style/logos/CC-Licentie.svg" alt="Naamsvermelding-GeenAfgeleideWerken 3.0 Nederland" width="115px" height="40px">`

Oplossingsrichting:
'px' verwijderen.

`<img src="https://tools.geostandaarden.nl/respec/style/logos/CC-Licentie.svg" alt="Naamsvermelding-GeenAfgeleideWerken 3.0 Nederland" width="115" height="40">`

**Comment by lvdbrink** [comment]
Tested, solved.
