### ISSUE TITLE
Bij gelijke titels van hoofdstukken/paragrafen wordt een gelijk id toegekend aan de sectie-ID's <h4>.

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/respec#130]
BEvinding:
----------
Bij gelijke titels van hoofdstukken/paragrafen wordt een gelijk id toegekend aan de sectie-ID's `<h4>`.

Dubbele ID

W3C-validator fout:
-------------------

Error: Duplicate ID basisscenario.
From line 1020, column 17; to line 1020, column 65
      `    <h4 id="basisscenario" resource="#basisscenario"><span `
                                
Treedt op bij:
--------------
  ` <h4 id="basisscenario" resource="#basisscenario"><span property="xhv:role" resource="xhv:heading"><span class="secno">3.2.1 </span>Basisscenario</span>`

**Comment by lvdbrink** [comment]
Treedt op als je in markdown werkt.

**Comment by lvdbrink** [comment]
Testen of dit nog optreedt en doorspelen aan w3c.

**Comment by thijsbrentjens** [comment]
Treedt nog steeds op, ook na merge v23.0.2

**Comment by thijsbrentjens** [comment]
Issue aangemaakt: https://github.com/w3c/respec/issues/1830

**Comment by thijsbrentjens** [comment]
Op help wanted gezet ivm melding bij W3C

**Comment by thijsbrentjens** [comment]
Fixed in w3c code, v23.0.4. Code merged in september2018 branch

**Comment by thijsbrentjens** [comment]
Fix deployed to prod
