### ISSUE TITLE
CC licentie naar versie 4.0

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#131]
De creative commons licentie moet naar versie 4.0 verwijzen. CC BY-ND-4.0.  Arnoud zoekt eerst nog uit welke variant van CC precies de juiste is. We gebruikten tot nu toe GeenAfgeeideWerken.

**Comment by lvdbrink** [comment]
Na overleg met Friso: zelfde variant, 4.0 versie.

**Comment by thijsbrentjens** [comment]
In develop is dit doorgevoerd in commit c52d07f68b9257a7a683facd99c3e9fbabc7291d

**Comment by lvdbrink** [comment]
Zie ook #128 #129. Dit zijn 2 bugs die in hetzelfde stukje code zitten, misschien handig om meteen mee te pakken.

**Comment by thijsbrentjens** [comment]
In de test build is dit doorgevoerd. Ook met de optie om andere licenties te configureren. Docs/voorbeelden volgen nog.
