### ISSUE TITLE
ReSpec documents not working in IE11

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#132]
Currently Geonovum ReSpec is not working when viewed with Internet Explorer 11. Console message: 

SCRIPT1006: ')' wordt verwacht
respec-geonovum.js (1,178821)

Needs further analysis.

**Comment by marcoscaceres** [comment]
As IE11 is discontinued software by Microsoft, we don’t support it. We support Microsoft Edge, however.

**Comment by marcoscaceres** [comment]
(Specs generated by us will work in IE - we just don’t have the time/resources to maintain support for IE11 😞)
