### ISSUE TITLE
Default email is geo-standaarden@geonovum.nl

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/respec#133]
Default email for consultatieVersie is geo-standaarden@geonovum.nl.
This is hard-coded in the respec.js. 

For consultatieVersie there should be a variabele in colofon, for example: "helpdesk" to refer to a custom helpdesk email, e.g. "imgeo@geonovum.nl"

**Comment by thijsbrentjens** [comment]
Een optie ingebouwd om een ander emailadres in te voeren: conf.emailComments, als dat niet opgegeven is wordt de geo-standaarden@geonovum.nl gebruikt.

**Comment by lvdbrink** [comment]
Tested, works!

**Comment by thijsbrentjens** [comment]
Docs at https://github.com/Geonovum/respec/wiki/emailComments
