### ISSUE TITLE
Aanpassen Status of Document naar documenttype

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/respec#138]
Bij definitieve versie wordt de volgende tekst getoond.

> Status of This Document
> 
> Dit is de definitieve versie van de standaard. Wijzigingen naar aanleiding van consultaties zijn doorgevoerd. De programmaraad van Geonovum heeft deze standaard goedgekeurd.

Dit lijkt in combinatie met specStatus 'GN-DEF'. 

Echter, bij specType 'PR' wordt ook deze tekst getoond. Dit zou aangepast moeten worden naar:

> Status of This Document
> 
> Dit is de definitieve versie van de **praktijkrichtlijn.** 

De volgende zinsneden zouden geschrapt/aangepast kunnen worden: 
_- Wijzigingen naar aanleiding van consultaties zijn doorgevoerd._ Praktijkrichtlijn hoeft niet formeel geconsulteerd te worden. Afstemming met werkveld / review door leveranciers is wel van toepassing.
_- De programmaraad van Geonovum heeft deze standaard goedgekeurd._ Een praktijkrichlijn hoeft niet goedgekeurd te worden door de programmaraad, immers informatief.

Dit geldt mogelijk ook voor andere documenttypen (specType).

**Comment by adbgnm** [comment]
De tekst uit het beheerdocument over praktijkrichtlijn zou ook toegevoegd kunnen worden aan status:

> Een praktijkrichtlijn is een product die informatie geeft, vaak met een technisch karakter, die nodig is voor het toepassen van een standaard. Een praktijkrichtlijn hoort altijd bij een standaard/norm.

**Comment by lvdbrink** [comment]
Goede suggestie. We gaan ernaar kijken.

**Comment by thijsbrentjens** [comment]
Dit is op zich redelijk goed aan te passen. Ik kan me voorstellen dat dit ook geldt voor andere types en voor andere statussen. Zijn jullie hier al tegenaan gelopen?

Bijvoorbeeld: kan er voor een praktijkrichtlijn een consultatieversie zijn? En wat moet dan de tekst zijn? 
Voor nu kan ik het inbouwen voor de praktijkrichtlijn, @lvdbrink @adbgnm  maar hier moeten we dus nog samen nog even wat verder naar kijken.
