### ISSUE TITLE
Respec werkt vaak pas na refresh

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#139]
Bij het openen van een Respec document in een browser wordt vaak alleen de tekst in index.html getoond, dwz respec javascript wordt blijkbaar niet uitgevoerd. Een browser refresh lost dit op. 

Nog niet goed uitgezocht hoe reproduceerbaar dit is. Bij mij gebeurt dit vaak in Opera. Andere gebruikers (uit het BRO team) rapporteren het ook.

**Comment by lvdbrink** [comment]
Update: soms gebeurt dit ook in Chrome. Ik heb niet scherp wanneer wel, wanneer niet. 

Ik weet niet of het ermee te maken heeft, maar Opera en Chrome rapporteren als dit zich voordoet de volgende script error. Na refresh doet deze error zich niet meer voor; 

> respec-geonovum.js:117 null "Script error." ErrorEvent
> (anonymous) @ respec-geonovum.js:117
> respec-geonovum.js:1 Uncaught TypeError: Cannot read property 'querySelector' of null
>     at Object.<anonymous> (respec-geonovum.js:1)
>     at Object.execCb (respec-geonovum.js:1)
>     at _.check (respec-geonovum.js:1)
>     at _.enable (respec-geonovum.js:1)
>     at Object.enable (respec-geonovum.js:1)
>     at _.<anonymous> (respec-geonovum.js:1)
>     at respec-geonovum.js:1
>     at each (respec-geonovum.js:1)
>     at _.enable (respec-geonovum.js:1)
>     at Object.enable (respec-geonovum.js:1)

**Comment by lvdbrink** [comment]
Ik heb als test https://broprogramma.github.io/GAR/ gekoppeld aan https://tools.geostandaarden.nl/respec/test/builds/respec-geonovum.js. Ik kan het refresh probleem zelf nu niet meer reproduceren. Gevraagd of dit bij anderen zich nog wel voordoet.

**Comment by lvdbrink** [comment]
Ik kom het toch nog regelmatig tegen. Het viel me op dat het niet gebeurde als ik een pagina lokaal open vanaf mijn file systeem of localhost. Wel als de pagina op github.io staat.

**Comment by lvdbrink** [comment]
Summary of this issue in English: 
When opening a ReSpec document in a browser, often only the contents of index.html are show, i.e. respec js is not executed apparently. A browser refresh solves this. 

Not clear how to reproduce this exactly. In my case it often happens in Opera (which I keep up to date). But has also happened in Chrome at least. Not sure if it's related, but both Opera and Chrome are reporting the script error I pasted above. This is reported before refresh; after refresh it is no longer reported. 

I tried if this was solved in a newer test build of Geonovum ReSpec. It seemed so at first, but later I was getting the problem again. 

One thing I noticed recently was that this doesn't seem to happen when I open a respec file from my local file system or localhost, but it does happen often when the page is loaded from github.io. 

@marcoscaceres maybe you can point us in the right direction here?

**Comment by marcoscaceres** [comment]
We were experiencing the same issue a few ReSpec versions back - but we seem to have fixed it (still a bit unsure what happened). Updating the ReSpec core to latest should hopefully help address that.
