### ISSUE TITLE
Linter staat geen h7 toe

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#140]
In BRO catalogi (in het deel dat gegenereerd wordt vanuit UML) komen secties voor met h7 headings. De linter staat blijkbaar alleen h2 t/m h6 headers toe. Dit resulteert _bij gebruik van onze Respec build in test_ in een Respec waarschuwing en rood onderstreepte tekst in de content van desbetreffende secties. Zie bv https://broprogramma.github.io/GAR/#attribuut-en-relatiesoort-details 

Gewenst is om wel `<h7>` te kunnen gebruiken. 

Nogmaals dit doet zich voor met https://tools.geostandaarden.nl/respec/test/builds/respec-geonovum.js

**Comment by thijsbrentjens** [comment]
Dit is relatief makkelijk aan te passen. Maar strikt genomen gaat dat tegen de HTML specs in:
"These elements have a rank given by the number in their name. The h1 element has the highest rank, the h6 element has the lowest rank, and two elements with the same name have equal rank."

h6 is het laagste niveau.

https://www.w3.org/TR/html53/sections.html#the-h1-h2-h3-h4-h5-and-h6-elements

**Comment by lvdbrink** [comment]
Dan ga ik het laten oplossen in de generator van de BRO catalogi (imvertor). Ik wil de HTML spec volgen.
