### ISSUE TITLE
Github link not working

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/respec#141]
In the new build for Geonovum the github conf link is ignored in the header. It should be used to create a link for Laatste werkversie like this

```
Laatste werkversie:
    https://geonovum.github.io/whitepaper-standaarden/
```

Note: take into account the organisationname of the Github repo: https://github.com/{org}/{repo} should be rewritten to https://{org}.github.io/{repo}/

If a github link is configured, always show the "Laatste werkversie" link

**Comment by lvdbrink** [comment]
Tested, works
