### ISSUE TITLE
Date translation

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#15]
At the top of /examples/whitepapertest, when viewed in a browser, it says: 
"Geonovum Praktijkrichtlijn Werkversie 09 March 2017"

'March' should be 'Maart' i.e. month names need to be translated to Dutch.

**Comment by marcoscaceres** [comment]
I added this feature to ReSpec on the W3C side. However,  we are blocked on resolving the issues from  https://github.com/Geonovum/respec/pull/16 

Once that lands, I can merge the upstream changes to address this. I'll send a pull request now.
