### ISSUE TITLE
Links naar issues werken niet

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#150]
## Important info

* https://geonovum.github.io/NEN3610-Linkeddata/
* ReSpec version: Geonovum aug2018
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
De link bovenin een respec document "Dien een melding in" geeft een 404. 

Links naar issues in de main body van documenten werken ook niet, tenzij je `issueBase` configureert in de respec config. Na het configureren van `issueBase` werken links naar issues in de body wel, maar de link naar issues in de header niet. 

Zie bv 
* een doc zonder `issueBase` https://broprogramma.github.io/GAR/#grondwatersamenstellingsonderzoek
* een doc met `issueBase` https://geonovum.github.io/NEN3610-Linkeddata/

In de vorige Geonovum ReSpec versie werkten beide volgens mij wel, zonder `issueBase` te configureren.

**Comment by lvdbrink** [comment]
Lukt het om hier nog naar te kijken voor deze milestone?

**Comment by thijsbrentjens** [comment]
Ik ga het proberen

**Comment by thijsbrentjens** [comment]
Dit lijkt opgelost met de nieuwe update van W3c code. Beide onderstaande voorbeeld configs werken:

```
...
github: "https://github.com/Geonovum/whitepaper-standaarden",
issueBase: "https://github.com/Geonovum/whitepaper-standaarden/issues/",
...
```
en 

```
...
github: "https://github.com/Geonovum/whitepaper-standaarden",
...
```

**Comment by thijsbrentjens** [comment]
W3C issue: https://github.com/w3c/respec/issues/1803
