### ISSUE TITLE
Some images not visible in local docs

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/respec#153]
## Important info

* URL to affected spec: locally hosted docs, for IMVG
* ReSpec version: 23.0.4
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
Some images are not shown. Docs are locally used/hosted, this issue needs more investigation for reproducing first, but I wanted to put it on the list already.

**Comment by thijsbrentjens** [comment]
In this doc images are not shown properly: https://geonovum.github.io/IMVG/#uitwerking

note to self: maybe we need some extra styling to explicitly set image sizes (width and height):

```
.figure img, .sidefigure img, figure img, .figure object, .sidefigure object, figure object {

    max-width: 100%;
    margin: auto;
    height: auto;
    width: auto;
}
```
Needs some testing.

**Comment by thijsbrentjens** [comment]
It seems that ReSpec adds a width="0" and height="0" attribute to a figure automatically.

**Comment by marcoscaceres** [comment]
oh, that's a bug. It should definitely not do that. It's supposed to add the a natural width and height.

**Comment by thijsbrentjens** [comment]
@marcoscaceres for now I'll add an extra CSS rule, to make sure images are shown, in addition to the existing one for figure img in base.css:
```
.figure img, .sidefigure img, figure img, .figure object, .sidefigure object, figure object {
 height: 100%;
 width: auto;
}
```

**Comment by thijsbrentjens** [comment]
Fixed after publication of update ReSpec build
