### ISSUE TITLE
Create a Markdown manual

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/respec#155]
## Important info
* general

## Description of problem
Which Markdown elements are supported and how to use them in Respec documents? E.g. can a note be created or a reference to a Github issue, or is this only supported in HTML?

There is a need for some documentation (manual / examples) on this.

**Comment by marcoscaceres** [comment]
> Which Markdown elements are supported and how to use them in Respec documents? 

We use https://marked.js.org/

Which conforms to this Markdown flavor:
https://github.github.com/gfm/

>  can a note be created or a reference to a Github issue, or is this only supported in HTML?

Currently documented here:
https://github.com/w3c/respec/wiki/format

Suggestions and improvements would be great!

**Comment by thijsbrentjens** [comment]
Thanks. The reference to the doc is clear, I missed the format page in the Wiki (sorry). So for notes and issues we should embed HTML in markdown. I'll forward this to my colleague that asked this.
