### ISSUE TITLE
English term 'section' used in generated section links

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#164]
## Important info

* URL to affected spec: https://broprogramma.github.io/GMN/
* ReSpec version: 23.7.4 GN version
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem
When using an emtpy anchor (e.g. `<a href="#buis-in-gebruik" class="sectionRef"></a>`) to refer to a section in the same document, the English term 'section' is used in the generated link text. 

> **section** 3.5.1 Aanduiding buis in gebruik in Grondwatermonitoringput

But what I was expecting?:
Dutch term 'paragraaf' should be used instead.

Two examples in https://broprogramma.github.io/GMN/#samenhang

**Comment by thijsbrentjens** [comment]
@marcoscaceres  thanks, we'll keen an eye on this.

@lvdbrink In the meantime I'll localize the prefix "section " for sectionRefs.

**Comment by thijsbrentjens** [comment]
A build including a fix is deployed at https://tools.geostandaarden.nl/respec/test/ 
@lvdbrink could you test the document with this build?

**Comment by lvdbrink** [comment]
Getest, is goed
