### ISSUE TITLE
Nummering subparagrafen in Respec tot maximaal 9

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/respec#182]
In respec wordt in de inhoudsopgaven tot maximaal 9 genummerd, terwijl in de content een subparagraaf 10 voorkomt.

Dit treedt onder meer op in de volgende BRO-documentatie: https://broprogramma.github.io/BHR-P/#global_class_ModelBHRPDeel2_Bodemclassificatie

**Comment by adbgnm** [comment]
![respec-bug-subparagrafen](https://user-images.githubusercontent.com/10595039/74182901-33df9800-4c44-11ea-8c61-f644de4c8e26.png)

**Comment by adbgnm** [comment]
Idem in https://broprogramma.github.io/BHR-G/#detail_attribute_Model_Grond_glauconietgehalteklasse

**Comment by thijsbrentjens** [comment]
(net besproken: ik ga een analyse doen, dan kijken wanneer e.e.a. op te pakken is, er volgen nu wat opmerkingen van die analyse)

Opmerkelijk: https://broprogramma.github.io/BHR-P/#detail_attribute_Model_Booronderzoek_vakgebied werkt wel, dit is met paragraaf: 
`5.3.1.12 vakgebied`

De nummering gaat mis bij de hogere subparagrafen op het 3e niveau, vanaf `5.3.23.10`

**Comment by thijsbrentjens** [comment]
Het heeft te maken met een fout in (W3C0 code om het TOC level te berekenen op basis van de paragraafnummering. Die verhoogt het TOC level (foutief) als er een nummer groter dan 10 in komt te staan. Omdat het maxTocLevel is opgegeven in de configuratie van dit document, gaat dit mis. Er komt een patch aan, doorvoeren in oorspronkelijke W3C code moet ik nog onderzoeken

**Comment by thijsbrentjens** [comment]
Op testomgeving staat een nieuwe build, lokaal getest en daarin was het issue verholpen.

Link naar build van respec script op testomgeving:
https://tools.geostandaarden.nl/respec/test/builds/respec-geonovum.js

@adbgnm als het voor jou makkelijk is hiermee te testen, kan je dat dan doen voor dat BRO document? Ik kan niet bij de repo daarvan om het zelf te doen.

Ik heb trouwens met een eigen test document getest en het issue is na deze fix opgelost

**Comment by lvdbrink** [comment]
Getest met https://broprogramma.github.io/BHR-P/ en werkt nu. 

![image](https://user-images.githubusercontent.com/7943515/82320817-2c165900-99d4-11ea-88cb-e58a15291707.png)

**Comment by thijsbrentjens** [comment]
sluiten als naar prod uitrol gedaan, wacht nu op bevestiging #184

**Comment by thijsbrentjens** [comment]
Productie uitrol is gedaan, dus issue sluiten
