### ISSUE TITLE
Fout in vorige en laatstgepubliceerde versie bij specType AL

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#184]
## Important info

* URL to affected spec: https://github.com/geonovum/disgeo-inhoud (ik heb de snapshot handmatig gecorrigeerd)

## Description of problem

Met deze settings:

```
specStatus: "GN-CV", 
specType: "AL", 
previousPublishDate: "2020-04-07",
previousMaturity: "CV",
```

Krijg ik 

**Vorige versie:**

`https://docs.geostandaarden.nl/disgeo/-al-hiso-20200407/`

Dus met een ontbrekende status vooraan de URL. Ik verwachtte: 

`https://docs.geostandaarden.nl/disgeo/cv-al-hiso-20200407/`

**Laatst gepubliceerde versie:**
`geen`

Dus een ontbrekende laatst gepubliceerde versie. Ik verwachtte: 
`https://docs.geostandaarden.nl/disgeo/hiso/`

**Comment by thijsbrentjens** [comment]
previousMaturity: dit moet een volledige status zijn, dus `GN-CV` ipv `CV`. Dit is dus nodig om via de conifguratie aan te passen (getest met @JvGldr )

**Comment by thijsbrentjens** [comment]
geen laatst gepubliceerde versie: we kwan erachter dat de controle of een document gepubliceerd is, beter kan. Die controle keek nu alleen naar een `publishDate`, wat een verplichte property is. Maar voor werkversies geef je geen publishDate op. De controle breiden we uit: als er een `previousPublishDate` is opgegeven, beschouwen we het doc ook als gepubliceerd.

**Comment by thijsbrentjens** [comment]
NB: de correctie komt alleen in het geonovum profiel

**Comment by thijsbrentjens** [comment]
@JvGldr en @lvdbrink ik heb een fix gedaan in de code, kunnen jullie bevestigen of dit nu goed werkt? De respec build staat alleen nog op de test omgeving, dus vervang in je document wel de verwijzing naar respec-geonovum.js:

`https://tools.geostandaarden.nl/respec/test/builds/respec-geonovum.js`

**Comment by JvGldr** [comment]
Ik heb het getest. publishDate weer leeggemaakt, en het werkt: de datum van het document is die van vandaag, en de link naar de vorige versie is ook weer goed!

Van: Thijs Brentjens <notifications@github.com>
Verzonden: vrijdag 12 juni 2020 14:12
Aan: Geonovum/respec <respec@noreply.github.com>
CC: Jan van Gelder <J.vanGelder@geonovum.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Geonovum/respec] Fout in vorige en laatstgepubliceerde versie bij specType AL (#184)


@JvGldr<https://github.com/JvGldr> en @lvdbrink<https://github.com/lvdbrink> ik heb een fix gedaan in de code, kunnen jullie bevestigen of dit nu goed werkt? De respec build staat alleen nog op de test omgeving, dus vervang in je document wel de verwijzing naar respec-geonovum.js:

https://tools.geostandaarden.nl/respec/test/builds/respec-geonovum.js

**Comment by lvdbrink** [comment]
Ik vertrouw erop als Jan het getest heeft dat het goed is :-)

**Comment by thijsbrentjens** [comment]
op productie gezet. Mocht het probleem zich nog voordoen, dan graag heropenen.
