### ISSUE TITLE
Change sodt section

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#3]
The Status of this Document section is W3C specific. Needs to be replaced by a (dutch lang) section with the appropriate text.

**Comment by lvdbrink** [comment]
Text for all statuses (the italic part): 
"Deze paragraaf beschrijft de status van dit document ten tijde van publicatie. Het is mogelijk dat er actuelere versies van dit document bestaan. Een lijst van Geonovum publicaties en de laatste gepubliceerde versie van dit document zijn te vinden op http://www.geonovum.nl/wegwijzer/standaarden. "

Status text for werkversie (editor's draft): 
"Dit is een werkversie die op elk moment kan worden gewijzigd, verwijderd of vervangen door andere documenten. Het is geen door de werkgroep goedgekeurde consultatieversie."

Status text for draft versie (working draft): 
"Dit is een door de werkgroep goedgekeurde consultatieversie. Commentaar over dit document kan gestuurd worden naar geo-standaarden@geonovum.nl". 

Final draft (similar to proposed rec): 
"Dit is een definitief concept van de nieuwe versie van de standaard. Wijzigingen naar aanleiding van consultaties zijn doorgevoerd. De programmaraad van Geonovum beoordeelt dit definitief concept. Keurt zij het goed, dan is er een nieuwe standaard."

**Comment by lvdbrink** [comment]
@dhvenema I added some text above for when you get to work on the sodt section.

**Comment by dhvenema** [comment]
This has been added to [sotd.html](https://github.com/Geonovum/respec/blob/develop/js/geonovum/templates/sotd.html). We may want to add more SotD elements in the future.

**Comment by marcoscaceres** [comment]
Nice one! 👍

**Comment by dhvenema** [comment]
We're missing sotd text for an official standard @lvdbrink

**Comment by lvdbrink** [comment]
Status text for final version: 
"Dit is de definitieve versie van de standaard. Wijzigingen naar aanleiding van consultaties zijn doorgevoerd. De programmaraad van Geonovum heeft deze standaard goedgekeurd. "
