### ISSUE TITLE
Change vertical text left top corner

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#4]
The vertical text that is displayed in the left top corner of documents, with a background color depending on document type, is W3C specific. 

"W3C" needs to be replaced by "Geonovum".

**Comment by marcoscaceres** [comment]
This is coming from w3c/styles. It sets the style sheet based on the document type.

**Comment by dhvenema** [comment]
Has been added to media/logos/*svg. We will have to put it somewhere online eventually.
