### ISSUE TITLE
Github-links

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#45]
Possibly add additional github-elements, such as: list of contributors (core/contrib.js), wiki-page, and gh-page.

**Comment by marcoscaceres** [comment]
Slightly related... there might be code in ReSpec that allows you to pull down the list of contributors directly form github... see "js/github.js"

**Comment by dhvenema** [comment]
Added werkversieGH (previously edDraftURL) is generated from the github links.

**Comment by dhvenema** [comment]
Linked to #65
