### ISSUE TITLE
ReSpec-icon in top right

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#47]
The ReSpec-icon the the top right, once clicked on "about ReSpec" it states: 

> ReSpec is a document production toolchain, **_with a notable focus on W3C specifications._**
> You can find more information in the documentation.
> Found a bug in ReSpec? File it!.

The part stating: "with a notable focus on W3C specifications" does not seem approriate in the Geonovum context and could perhaps be left out or changed to: "...but also used by other standardisation organisation." 

It's defined in ui/about-respec.js:
```javascript
const $halp = $("<div><p>ReSpec is a document production toolchain, with a notable focus on W3C specifications.</p></div>");
$("<p>You can find more information in the <a href='https://w3.org/respec/'>documentation</a>.</p>").appendTo($halp);
$("<p>Found a bug in ReSpec? <a href='https://github.com/w3c/respec/issues'>File it!</a>.</p>").appendTo($halp);
```

**Comment by marcoscaceres** [comment]
@dhvenema, probably best to file this over on the upstream repository. We can also make a custom about box for Geonovum. If I recall correctly, the UIs are brought in as part of the profile - so we can just make a new about box.

**Comment by dhvenema** [comment]
Added a new directory in geonovum/ui with the 4 UI files. Added various translations to the respec-ui buttons.
