### ISSUE TITLE
Change h2 below title containing "W3C" [doctype] [date] 

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#5]
The h2 which is generated in the header, containing the text "W3C" followed by the document type (long name) and the date, is W3C specific. We want to change "W3C" to "Geonovum". 

I changed geonovum/headers.js line 101: 'w3c/templates/compiled'  to 'geonovum/templates/compiled'. 

In headers.html I changed line 21, starting '`<h2>{{#if prependW3C}}W3C`'  to '`<h2>{{#if prependW3C}}Geonovum'`. 

Then ran 

handlebars -a js/geonovum/templates/headers.html -f js/geonovum/templates/compiled.js

Now I get a TypeError: headersTmpl is not a function

**Comment by marcoscaceres** [comment]
strange... I just ran:

```
handlebars -a js/geonovum/templates/headers.html -f js/geonovum/templates/compiled.js
```

here and it worked ok. I'll check in the compiled version.

**Comment by marcoscaceres** [comment]
Ok, pushed the compiled header up to develop.

**Comment by marcoscaceres** [comment]
Ah, I misunderstood... I see the problem now... headersTmpl is indeed throwing.

**Comment by marcoscaceres** [comment]
Ok, got it! Need to run:

```
handlebars -a js/*/templates/*.html js/*/templates/*.css -f js/*/templates/compiled.js
```

I will change the rule in package.json for:

```
npm run build:hb
```

To run as above.

**Comment by marcoscaceres** [comment]
(I've made the change above - I've updated the develop branch also)

**Comment by marcoscaceres** [comment]
@lvdbrink, been poking at building on Windows for last few days, but still haven't had much success getting it working through NPM.

However, it does work ok if you build the templates directly in the command line: 

```
handlebars -a js/geonovum/templates/*.html js/geonovum/templates/*.css js/core/templates/webidl-contiguous/*.html -f js/templates.js
```

That will at least let you build the templates while we work something out. I might need to file a bug upstream on Handlebars, as I can't figure out why it's not working :( 

If you have any ideas, let me know. 

(Note in the above, I don't imagine you will be using  the WebIDL templates in your specs, right? We can probably exclude that - Web IDL is a "interface definition language" for defining JavaScript interfaces and it's only really used by Web Browsers.)

**Comment by marcoscaceres** [comment]
fixed typo in comment above.

**Comment by lvdbrink** [comment]
When I try to build directly using the command you gave, handlebars throws an error... 

C:\Users\lvandenbrink\AppData\Roaming\npm\node_modules\handlebars\bin\handlebars:120
    throw err;
    ^
Error: Unable to open template file "js/geonovum/templates/*.html"
    at C:\Users\lvandenbrink\AppData\Roaming\npm\node_modules\handlebars\dist\cjs\precompiler.js:107:25
    at FSReqWrap.oncomplete (fs.js:123:15)

When I do this, it works: 
handlebars -a js/geonovum/templates/headers.html -f js/templates.js

Something to do with the wildcard?

**Comment by marcoscaceres** [comment]
Yeah, Windows doesn't seem to know how to handle wildcards, but Git Bash seems to handle them ok. Let me try in cmd.exe also.

**Comment by lvdbrink** [comment]
I have Windows 7 which also has Powershell, Git Shell is based on that. In Git Shell I can do: 

dir js/geonovum/templates/*.html

Which works i.e. it gives me all files matching the wildcard. In cmd this doesn't work. 

But using a wildcard with the handlebars command fails as I said.

**Comment by marcoscaceres** [comment]
I filed a bug with Handlebars: https://github.com/wycats/handlebars.js/issues/1318

**Comment by marcoscaceres** [comment]
Just to be clear, on *nix systems, the OS handles wildcard expansion - but in Windows, the application is supposed to handle wildcard expansion. 

What we might need to do is run [glob](https://github.com/isaacs/node-glob) to expand the paths on Windows, then pipe the expanded file names into handlebars.

**Comment by dhvenema** [comment]
This should be fixed with the new build option: 
> npm run hb:build-geo
