### ISSUE TITLE
Add document types

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#6]
We want to customize / translate W3C document type names or add our own document types. Geonovum has the following document types: 
- Norm 
- Standaard 
- Informatiemodel 
- Praktijkrichtlijn 
- Handreiking
- Werkafspraak
(Geonovum needs to analyse these doc types to see which W3C doc type they resemble. The first three are all similar to rec and the last three similar to BP.)

And the following statusses:
- werkversie (editor's draft)
- draft versie (working draft)
- Final draft (similar to proposed rec)

**Comment by dhvenema** [comment]
I'm going to add a new config element specType for the document types as listed above. The specStatus would include: 
* Werkversie
* Draft versie
* Final draft
* ~~(Officiële) Standaard~~ Definitief
* ~~Onofficieel~~
* ~~Basis~~ Document

**Comment by dhvenema** [comment]
These have been added to [headers.js](https://github.com/Geonovum/respec/blob/develop/js/geonovum/headers.js). I've tried to clean up the code and remove most of what we don't use.
