### ISSUE TITLE
Generate issueBase from github-link

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#65]
When a user defines a data-number in an issue, an href is generated in issues-notes.js if an issueBase is set in the config. The Geonovum-respec includes a github config option that could be used to generate the link for that issueBase. In probably all cases the issues would be posted on github, therefore have the github link as a default issueBase would be sufficient and make issueBase obsolete.

This could be accomplished by adjusted issues-notes.js, however then W3C-respec releases would be out of sync.

**Comment by marcoscaceres** [comment]
It's probably not necessary to make `issueBase` obsolete, but we could definitely deprecate it and just make it internal to ReSpec. So, "github:" should just set `conf.issueBase` (if issue base is not declared) and then any module that relies on `issueBase` will just work. 

I'd like to eventually migrate `github` over to ReSpec core. Will try to work on that next quarter.
