### ISSUE TITLE
Vertalingen in l10n.js

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#74]
De W3C-respec heeft nieuwe woorden toegevoegd aan de l10n.js die vertaald kunnen worden naar Nederlands, indien gewenst. Dit zijn:
* Commit history
* Participate

**Comment by lvdbrink** [comment]
Participate: 'Doe mee"

Commit history: moeilijk te vertalen, dit is zo'n specifieke technische term. Laat maar staan in het Engels.

**Comment by dhvenema** [comment]
Of Commit Historie? Herziening Historie? Revisie Historie?

**Comment by dhvenema** [comment]
Het wordt: Revisiehistorie
