### ISSUE TITLE
Add clickable SVG in leaflet figures

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#83]
Now that https://github.com/Geonovum/respec/issues/49 is in place. It would be better if user could click on UML elements and redirect them to the appropriate sections in the HTML-document. This could be achieved by generating an SVG-figure and incuding that in leafletfigures.js. A possible solution could be to implement the d3-library.

**Comment by dhvenema** [comment]
This could possibly be linked/directed to "technisch register" and its UML's.

**Comment by dhvenema** [comment]
See sample for testing: http://tools.geostandaarden.nl/respec/media/logos/sample-imgeo.svg

**Comment by lvdbrink** [comment]
We have clickable UML diagrams now (not SVG)
