### ISSUE TITLE
Leaflet doesn't export to HTML

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#85]
When using the export to HTML button in ReSpec, figures using leaflet don't export properly.

**Comment by marcoscaceres** [comment]
heh, I should have thought of this... so what's happening is, Leaflet is running when we generate the document, but when you export the document, Leaflet gets thrown out (a long with the rest of ReSpec). 

Obviously, we don't want it to do that... so we need to do a couple of additional things. 

* [ ] add Leaflet as an external dependency. 
* [ ] add code that "re-binds" Leaflet to images after the document generated. 

It's a bit of work - but definitely doable.

**Comment by dhvenema** [comment]
Closed with https://github.com/Geonovum/respec/pull/99
