### ISSUE TITLE
Wiki-page

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#9]
Since we are changing some elements in the configuration options as well as the javascripts, perhaps we ougth to make a wiki to elaborate on what's possible and how it works.

**Comment by marcoscaceres** [comment]
Indeed. You can add things directly into https://github.com/Geonovum/respec/wiki 

If you have ideas about what you would like to add, let me know... there might be options that are useful "upstream".

**Comment by dhvenema** [comment]
I have created a simple setup, wherein I have linked certain configuration options to the W3C-wiki: https://github.com/Geonovum/respec/wiki
