### ISSUE TITLE
Change thisVersion latestPublished

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#93]
As a user it would be good if thisVersion refers to the actual thisVersion. Therefore, if a document is a "werkversie" it should refer to a github-page, and when it's a cv/vv/def it should refer to a docs.geostandaarden-page.

Something similar happens to latestPublished. As a user it would be good if the page doesn't exist (i.e. there is no latestPublishedVersion yet), that it is not be included in the header.

**Comment by dhvenema** [comment]
thisVersion solved in #98

**Comment by thijsbrentjens** [comment]
Implemented in geonovum header: if no publishDate is configured, then the latestVersion ("latestPublished") is not provided.

**Comment by lvdbrink** [comment]
Working
